### ISSUE TITLE
demo结果

### ISSUE THREAD

**Issue by paraself** [Lelouch-cc/todo-demo#1]
## 基础项目：

- 用列表展示全部的todo任务（5分）
- 实现任务项目的增加、删除、修改（10分）
- 实现勾选任务完成（5分）
- 用全局状态管理工具（如Vuex，Redux等），展示任务的整体情况。如任务总数，完成数量（5分）
- 采用浏览器本地存储（5分）

## 进阶项目：

- 用async/await + Promise封装对于浏览器本地数据的操作，以便在未来替换成实际的接口（10分）
- 完善的错误处理机制，错误提示（2/5分）

> commit里使用了异步的方法
https://github.com/Lelouch-cc/todo-demo/blob/57e4aaf1cae8a46bd97b1fb3395cc5ca0c7288bf/src/store/mutations.ts#L10
这里有这个问题：如果是想先处理同步数据，然后在异步保存回localStorage，那如果localStorage保存出错，就会造成同步数据和持久化数据（localStorate）的不一致

- 浏览器离线数据存储以及PWA渐进式（0/10分）
- 使用Github进行版本控制，区分不同的分支进行新功能的开发（5/10分）
> 有创建分支但是从分支的图线上看git flow不够清晰
- 遵循angular commit format格式，并集成语义化版本发布，自动生成changelog（0/10分）
> changelog似乎加上了但是没有真正生成changelog的内容
- 使用Typescript, 或者TSX（10/20分）
>  vuex中有很多any类型，没有根据业务创建泛型，大量使用any让ts没有了意义
- 有良好的编码习惯，包括变量命名，接口注释，参数注释，类名，私有/公有成员方法的区分，临时变量的命名等等。（5/10分）
> 变量命名，接口注释，参数注释，类名这几部分不规范
- 有清晰合理的模块设计。使用面向对象原则对项目进行合理的架构。（10/20分）
> 暂时没体现出完整的面向对象的范式，封装继承多态等
- 使用函数式编程操作数据，包括但不限于Lodash，Ramda，Elm，PureScript等框架（0/20分）
> 没有使用
- 使用RxJS进行用户操作事件的封装，以便未来兼容多数据源的需求（todolist里的item可能来自ws接口）(0/20分)
> 没有使用
- 集成jest测试并设置pull request时候自动执行测试用例，同时将结果显示在pull request中（8/10分）
> 项目中没有pr
- 将静态页面集成到github pages，并利用常用的CI工具进行自动构建，自动测试，自动发布（10/20分）
> 缺少自动构建部分

得分90 / 总分 195 = 46%

**Comment by Lelouch-cc** [comment]
谢谢指出的问题，以后会多多注意并改进。
